name: Scheduled Build if Main Changes

on:
  schedule:
    # Runs every 5 minutes for testing
    - cron: '*/5 * * * *'

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Get the latest commit hash of main
    - name: Get latest commit on main
      id: get_latest_commit
      run: echo "::set-output name=latest_commit::$(git rev-parse origin/main)"

    # Step 3: Compare commit hashes
    - name: Check if main has new commits
      id: check_changes
      run: |
        PREVIOUS_COMMIT=$(cat .last-successful-commit 2>/dev/null || echo "")
        LATEST_COMMIT=${{ steps.get_latest_commit.outputs.latest_commit }}

        echo "Previous commit: $PREVIOUS_COMMIT"
        echo "Latest commit: $LATEST_COMMIT"

        if [ "$PREVIOUS_COMMIT" = "$LATEST_COMMIT" ]; then
          echo "::set-output name=build_needed::false"
        else
          echo "::set-output name=build_needed::true"
        fi

    # Step 4: Run the build if needed
    - name: Run Build
      if: steps.check_changes.outputs.build_needed == 'true'
      run: |
        echo "Running build process..."
        # Your build commands go here

        # Save the commit hash for the next run
        echo "${{ steps.get_latest_commit.outputs.latest_commit }}" > .last-successful-commit

    # Step 5: Save the .last-successful-commit file for the next workflow run
    - name: Upload commit state
      if: steps.check_changes.outputs.build_needed == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: last-successful-commit
        path: .last-successful-commit
