name: Scheduled Build if Main Changes

on:
  workflow_dispatch:
  schedule:
    # Runs every 5 minutes for testing
    - cron: '*/5 * * * *'

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download previous commit state
      uses: actions/download-artifact@v4
      with:
        name:
        github-token: ${{ secrets.GH_PAT }}
      continue-on-error: true  # Proceed even if the artifact is missing

    - name: Ensure previous commit exists
      run: |
        # Create fallback if artifact is missing
        if [ ! -f .last-successful-commit ]; then
          echo "No previous commit found, creating fallback."
          echo "" > .last-successful-commit
        fi

    - name: Compare commits
      id: check_changes
      run: |
        PREVIOUS_COMMIT=$(cat .last-successful-commit)
        LATEST_COMMIT=$(git rev-parse origin/main)

        echo "Previous commit: $PREVIOUS_COMMIT"
        echo "Latest commit: $LATEST_COMMIT"

        if [ "$PREVIOUS_COMMIT" = "$LATEST_COMMIT" ]; then
          echo "build_needed=false" >> $GITHUB_OUTPUT
        else
          echo "build_needed=true" >> $GITHUB_OUTPUT
        fi

    - name: Run Build
      if: steps.check_changes.outputs.build_needed == 'true'
      run: |
        echo "Running build process..."
        echo "$(git rev-parse origin/main)" > .last-successful-commit

    - name: Upload commit state
      if: steps.check_changes.outputs.build_needed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: last-successful-commit
        path: .last-successful-commit        
        include-hidden-files: true

