name: Scheduled Build if Main Changed Simpler

on:
  workflow_dispatch:
  schedule:
    - cron: '05 10 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      build_needed: ${{ steps.set-decision.outputs.build_needed }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine Base SHA
      id: base-sha
      run: echo "BASE_SHA=$(git rev-parse origin/main)" >> $GITHUB_ENV
      
    - name: Determine Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch_depth: "100"
        base_sha: ${{ env.BASE_SHA }}
      continue-on-error: true

    - name: Determine if Build is Needed
      id: set-decision
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "Manual trigger detected. Forcing build."
          echo "build_needed=true" >> $GITHUB_OUTPUT
        elif [ "${{ steps.changed-files.outcome }}" == "failure" ]; then
          echo "Failure in detecting changes. Defaulting to build."
          echo "build_needed=true" >> $GITHUB_OUTPUT
        elif [ "${{ steps.changed-files.outputs.all_changed_files }}" != "" ]; then
          echo "Changes detected: ${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Build needed."
          echo "build_needed=true" >> $GITHUB_OUTPUT
        else
          echo "No changes detected. Skipping build."
          echo "build_needed=false" >> $GITHUB_OUTPUT
        fi

  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.build_needed == 'true'
    steps:
    - name: Run Build
      run: |
        echo "Running build process..."
